// <auto-generated />
namespace SolarSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedetailedprofilemodeltoprofile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedetailedprofilemodeltoprofile));
        
        string IMigrationMetadata.Id
        {
            get { return "201704080014008_change detailedprofile model to profile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
